main: "com.act.chat.ActChat"
name: "Act-Chat"
version: "1.0"
api-version: "1.20"

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.22

commands:
  chat:
    usage: "/<command> [켜기/끄기]"
    aliases:
      - "채팅"
    description: "Chat Command"
    permission: "act.admin"